default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5


development:
  <<: *default
  database: fullstack-challenge
  host: localhost
  port: 5432
  username: andrey
  password: postgres

test:
  <<: *default
  database: testdb
  host: localhost
  port: 5432
  username: andrey
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  url: <%= ENV['DATABASE_URL'] %>
