default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5


development:
  <<: *default
  database: fullstack-challenge

test:
  <<: *default
  database: testdb

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  url: <%= ENV['DATABASE_URL'] %>
